### PR TITLE
Add Last.fm scrobbling

### PR DESCRIPTION
**Pull request by jillro**
Implement Last.fm scrobbling thanks to [pylast](https://github.com/pylast/pylast).

By default, Last.fm scrobbling is not enabled.

To enable Last.fm scrobbling, they can pass your `--lastfm_username`, `--lastfm_password`, `--lastfm_api_key` and `--lastfm_api_secret` on the command line.
They can also use `lastfm_credentials.json` and pass `--lastfm_credentials lastfm_credentials.json` to the command line.

The user needs to explicitly pass the name of the credentials file, otherwise the Last.fm module will not launch.

### CODE REVIEW

**Comment by cadavre** [comment]
I believe lastfm_credentials.json format is missing in README. :)

```
{
  "username": "lastfmusername",
  "password": "lastfmpassw0rd",
  "api_key": "generatedkey",
  "api_secret": "generatedsecret"
}
```

Is this correct?

**Comment by jillro** [comment]
This is correct, I thought providing a `lastfm_credentials.json.dist` would be enough.

**Comment by cadavre** [comment]
True, I didn't noticed `.dist`, my fault.

**Comment by jillro** [comment]
It wasn't clear enough, so I mentioned it :) I thinks this way is a good compromise not to pollute README with too much code.

**Comment by cadavre** [comment]
Perfect! Great work @guilro ! There's no point to include my code here as yours is much more complete. Thank you!

**Comment by Fornoth** [comment]
Good work! I'll try and get this tested sometime in the next few weeks

**Comment by cadavre** [comment]
It is already tested for several weeks now by me. No problems, ready to merge.

**Comment by Fornoth** [comment]
Thanks for the pull request! Sorry it took so long to merge

**Comment by thoughtgap** [comment]
Amazing, thank you so much for this feature! 
Would it be possible to create a new packaged release? It's not included in the 0.0.3 installer.

**Pull request merged**
