### PR TITLE
Add volume range setting

### PR DESCRIPTION
**Pull request by chukysoria**
Add a volume range setting -- useful for the Raspberry Pi's built-in DAC

### CODE REVIEW

**Comment by chukysoria** [comment]
Fixes #22

**Comment by oschwede** [comment]
When I'm using --dbrange, a segfault happens when trying to access the webinterface. The funny thing is, when turning on debugging by using -d switch, the segfault does not happen anymore.

I'm running on Arch Linux, pyalsaaudio is 0.8.2. Any ideas what could cause this problem?

**Comment by maumi** [comment]
Try to comment out 
Print zerovars 
in connect.py

**Comment by oschwede** [comment]
Thanks for your help :) After uncommenting it runs fine.

But I'm still wondering, why this issues appears when using --dbrange option, because non of the changes in this pull request affect the zeroconf code. When I have some time, I will try to investigate that.

**Comment by Fornoth** [comment]
@chukysoria Pull request looks good, except can you change the option to represent it better, maybe something like `--min-vol-range`?
@oschwede if you can come to the [gitter channel](https://gitter.im/sashahilton00/spotify-connect-resources) I can help you debug that (if you wanna get started, try running it like `LD_LIBRARY_PATH=$PWD python -m trace -t --ignore-dir venv --ignore-dir /usr main.py`)

**Comment by EyMaddis** [comment]
any updates?

**Comment by Fornoth** [comment]
I'll try merging this in the next week or two

**Comment by oschwede** [comment]
I tried to debug the segfault today, but I cannot reproduce it anymore. Not even with the code from beginning of march. When I checkout this particular pull request with "git fetch origin pull/34/head:test && git checkout test", everythings is fine.

Avahi has been installed on my computer a few weeks ago, maybe that makes a difference? Although uninstalling Avahi does not bring back the segfault.

**Pull request merged**
