### PR TITLE
Add Dockerfile and wrapper script

### PR DESCRIPTION
**Pull request by djmaze**

### CODE REVIEW

**Comment by djmaze** [comment]
@Fornoth, I added a link to some detailed preliminary documentation on how to install Docker on a Pi. Maybe this makes more sense now.

**Comment by empi89** [comment]
Works like a charm, should definitely be merged to master! Just tested it with hypriot on RPi2. 

You may add to the README that the appkey has to be added before building with docker.

**Comment by djmaze** [comment]
Thanks @empi89, I added a hint to the README.

**Comment by djmaze** [comment]
@Fornoth: I just added some instructions on how to use my nighly-built chroot. This is ready to merge, from my point of view.

**Pull request merged**
